version: '3'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - ./db/:/data/db
    ports:
      - '27017:27017'
    restart: always

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - '8006:8006'
    restart: always
    depends_on:
      - mongo_db
    volumes:
      - .:/app
      - /app/products/node_modules

  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    container_name: customer
    ports:
      - '8005:8005'
    restart: always
    depends_on:
      - mongo_db
    volumes:
      - .:/app
      - /app/customer/node_modules

  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping
    ports:
      - '8007:8007'
    restart: always
    depends_on:
      - mongo_db
    volumes:
      - .:/app
      - /app/shopping/node_modules

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    container_name: nginx-proxy
    depends_on:
      - products
      - customer
      - shopping
    ports:
      - "81:81"

volumes:
  mongo_db: {}