version: '3'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo_db:/data/db
    ports:
      - '27012:27017'
    restart: always
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes:
  mongo_db: {}